<?xml version="1.0" encoding="UTF-8"?>

<definitions
    xmlns="http://schemas.xmlsoap.org/wsdl/"
    xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema" name="EchoXMLReaderServiceWrapper" targetNamespace="http://enterprise.netbeans.org/bpel/EchoXMLReaderServiceWrapper" xmlns:tns="http://enterprise.netbeans.org/bpel/EchoXMLReaderServiceWrapper" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:ns="http://service.xml.soen487/">
    <import location="EchoXMLReaderService.wsdl" namespace="http://service.xml.soen487/"/>
    <plnk:partnerLinkType name="EchoXMLReaderLinkType">
        <plnk:role name="EchoXMLReaderRole" portType="ns:EchoXMLReader"/>
    </plnk:partnerLinkType>
</definitions>
