
package soen487.wscat.services.client;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10-b140803.1500
 * Generated source version: 2.2
 * 
 */
@WebService(name = "WSCATService", targetNamespace = "http://services.wscat.soen487/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WSCATService {


    /**
     * 
     * @param uri
     * @throws ParserConfigurationException_Exception
     * @throws SAXException_Exception
     * @throws IOException_Exception
     * @throws InterruptedException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "trainOnURI", targetNamespace = "http://services.wscat.soen487/", className = "soen487.wscat.services.client.TrainOnURI")
    @ResponseWrapper(localName = "trainOnURIResponse", targetNamespace = "http://services.wscat.soen487/", className = "soen487.wscat.services.client.TrainOnURIResponse")
    @Action(input = "http://services.wscat.soen487/WSCATService/trainOnURIRequest", output = "http://services.wscat.soen487/WSCATService/trainOnURIResponse", fault = {
        @FaultAction(className = ParserConfigurationException_Exception.class, value = "http://services.wscat.soen487/WSCATService/trainOnURI/Fault/ParserConfigurationException"),
        @FaultAction(className = SAXException_Exception.class, value = "http://services.wscat.soen487/WSCATService/trainOnURI/Fault/SAXException"),
        @FaultAction(className = IOException_Exception.class, value = "http://services.wscat.soen487/WSCATService/trainOnURI/Fault/IOException"),
        @FaultAction(className = InterruptedException_Exception.class, value = "http://services.wscat.soen487/WSCATService/trainOnURI/Fault/InterruptedException")
    })
    public void trainOnURI(
        @WebParam(name = "URI", targetNamespace = "")
        String uri)
        throws IOException_Exception, InterruptedException_Exception, ParserConfigurationException_Exception, SAXException_Exception
    ;

    /**
     * 
     * @param wsdlFile
     * @throws ParserConfigurationException_Exception
     * @throws SAXException_Exception
     * @throws IOException_Exception
     * @throws InterruptedException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "trainOnWSDL", targetNamespace = "http://services.wscat.soen487/", className = "soen487.wscat.services.client.TrainOnWSDL")
    @ResponseWrapper(localName = "trainOnWSDLResponse", targetNamespace = "http://services.wscat.soen487/", className = "soen487.wscat.services.client.TrainOnWSDLResponse")
    @Action(input = "http://services.wscat.soen487/WSCATService/trainOnWSDLRequest", output = "http://services.wscat.soen487/WSCATService/trainOnWSDLResponse", fault = {
        @FaultAction(className = ParserConfigurationException_Exception.class, value = "http://services.wscat.soen487/WSCATService/trainOnWSDL/Fault/ParserConfigurationException"),
        @FaultAction(className = SAXException_Exception.class, value = "http://services.wscat.soen487/WSCATService/trainOnWSDL/Fault/SAXException"),
        @FaultAction(className = IOException_Exception.class, value = "http://services.wscat.soen487/WSCATService/trainOnWSDL/Fault/IOException"),
        @FaultAction(className = InterruptedException_Exception.class, value = "http://services.wscat.soen487/WSCATService/trainOnWSDL/Fault/InterruptedException")
    })
    public void trainOnWSDL(
        @WebParam(name = "wsdlFile", targetNamespace = "")
        String wsdlFile)
        throws IOException_Exception, InterruptedException_Exception, ParserConfigurationException_Exception, SAXException_Exception
    ;

    /**
     * 
     * @param repoURI
     * @return
     *     returns java.util.List<java.lang.String>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "submitWSDLRepo", targetNamespace = "http://services.wscat.soen487/", className = "soen487.wscat.services.client.SubmitWSDLRepo")
    @ResponseWrapper(localName = "submitWSDLRepoResponse", targetNamespace = "http://services.wscat.soen487/", className = "soen487.wscat.services.client.SubmitWSDLRepoResponse")
    @Action(input = "http://services.wscat.soen487/WSCATService/submitWSDLRepoRequest", output = "http://services.wscat.soen487/WSCATService/submitWSDLRepoResponse")
    public List<String> submitWSDLRepo(
        @WebParam(name = "repoURI", targetNamespace = "")
        String repoURI);

    /**
     * 
     * @param wsdlFile
     * @return
     *     returns java.lang.String
     * @throws IOException_Exception
     * @throws InterruptedException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "submitWSDLToAnalyze", targetNamespace = "http://services.wscat.soen487/", className = "soen487.wscat.services.client.SubmitWSDLToAnalyze")
    @ResponseWrapper(localName = "submitWSDLToAnalyzeResponse", targetNamespace = "http://services.wscat.soen487/", className = "soen487.wscat.services.client.SubmitWSDLToAnalyzeResponse")
    @Action(input = "http://services.wscat.soen487/WSCATService/submitWSDLToAnalyzeRequest", output = "http://services.wscat.soen487/WSCATService/submitWSDLToAnalyzeResponse", fault = {
        @FaultAction(className = IOException_Exception.class, value = "http://services.wscat.soen487/WSCATService/submitWSDLToAnalyze/Fault/IOException"),
        @FaultAction(className = InterruptedException_Exception.class, value = "http://services.wscat.soen487/WSCATService/submitWSDLToAnalyze/Fault/InterruptedException")
    })
    public String submitWSDLToAnalyze(
        @WebParam(name = "wsdlFile", targetNamespace = "")
        String wsdlFile)
        throws IOException_Exception, InterruptedException_Exception
    ;

}
