
package soen487.wscat.services.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10-b140803.1500
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "WSCATServiceService", targetNamespace = "http://services.wscat.soen487/", wsdlLocation = "http://localhost:8080/PM1Official/WSCATServiceService?wsdl")
public class WSCATServiceService
    extends Service
{

    private final static URL WSCATSERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException WSCATSERVICESERVICE_EXCEPTION;
    private final static QName WSCATSERVICESERVICE_QNAME = new QName("http://services.wscat.soen487/", "WSCATServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/PM1Official/WSCATServiceService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        WSCATSERVICESERVICE_WSDL_LOCATION = url;
        WSCATSERVICESERVICE_EXCEPTION = e;
    }

    public WSCATServiceService() {
        super(__getWsdlLocation(), WSCATSERVICESERVICE_QNAME);
    }

    public WSCATServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), WSCATSERVICESERVICE_QNAME, features);
    }

    public WSCATServiceService(URL wsdlLocation) {
        super(wsdlLocation, WSCATSERVICESERVICE_QNAME);
    }

    public WSCATServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, WSCATSERVICESERVICE_QNAME, features);
    }

    public WSCATServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WSCATServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns WSCATService
     */
    @WebEndpoint(name = "WSCATServicePort")
    public WSCATService getWSCATServicePort() {
        return super.getPort(new QName("http://services.wscat.soen487/", "WSCATServicePort"), WSCATService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WSCATService
     */
    @WebEndpoint(name = "WSCATServicePort")
    public WSCATService getWSCATServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://services.wscat.soen487/", "WSCATServicePort"), WSCATService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (WSCATSERVICESERVICE_EXCEPTION!= null) {
            throw WSCATSERVICESERVICE_EXCEPTION;
        }
        return WSCATSERVICESERVICE_WSDL_LOCATION;
    }

}
